# Generated by Django 5.1.7 on 2026-04-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidateprofile_remove_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateProfile',
        ),
    ]
