# Generated by Django 5.1.7 on 2026-05-08 14:52

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='candidateskill',
            options={'ordering': ['candidate', 'skill']},
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['txt', 'pdf', 'doc', 'docx'])]),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['user'], name='candidates__user_id_61b599_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['full_name'], name='candidates__full_na_ebaabd_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateskill',
            index=models.Index(fields=['candidate'], name='candidates__candida_cea4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateskill',
            index=models.Index(fields=['skill'], name='candidates__skill_i_32a057_idx'),
        ),
    ]
